package com.ttx.my.spring.boot.data.jpa.thymleaf.dto;
// Generated Jul 17, 2016 1:38:06 AM by Hibernate Tools 5.1.0.Alpha1

/**
 * EmpDetailsView generated by hbm2java
 */
public class EmpDetailsViewDTO implements java.io.Serializable {

	private EmpDetailsViewIdDTO id;

	public EmpDetailsViewDTO() {
	}

	public EmpDetailsViewDTO(EmpDetailsViewIdDTO id) {
		this.id = id;
	}
	public EmpDetailsViewIdDTO getId() {
		return this.id;
	}

	public void setId(EmpDetailsViewIdDTO id) {
		this.id = id;
	}

}
