package com.ttx.my.spring.boot.data.jpa.thymleaf.dto;
// Generated Jul 17, 2016 1:38:06 AM by Hibernate Tools 5.1.0.Alpha1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.ttx.my.spring.boot.data.jpa.thymleaf.entity.Jobs;

/**
 * Employees generated by hbm2java
 */
public class EmployeesDTO implements java.io.Serializable {

	private int employeeId;
	private DepartmentsDTO departments;
	private JobsDTO jobs;
	private EmployeesDTO employees;
	private String firstName;
	private String lastName;
	private String email;
	private String phoneNumber;
	private Date hireDate;
	private BigDecimal salary;
	private BigDecimal commissionPct;
	private Set<DepartmentsDTO> departmentses = new HashSet<DepartmentsDTO>(0);
	private Set<EmployeesDTO> employeeses = new HashSet<EmployeesDTO>(0);
	private Set<JobHistoryDTO> jobHistories = new HashSet<JobHistoryDTO>(0);

	public EmployeesDTO() {
	}

	public EmployeesDTO(int employeeId, JobsDTO jobs, String lastName, String email, Date hireDate) {
		this.employeeId = employeeId;
		this.jobs = jobs;
		this.lastName = lastName;
		this.email = email;
		this.hireDate = hireDate;
	}

	public int getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}

	public DepartmentsDTO getDepartments() {
		return this.departments;
	}

	public void setDepartments(DepartmentsDTO departments) {
		this.departments = departments;
	}

	public JobsDTO getJobs() {
		return this.jobs;
	}

	public void setJobs(JobsDTO jobs) {
		this.jobs = jobs;
	}

	public EmployeesDTO getEmployees() {
		return this.employees;
	}

	public void setEmployees(EmployeesDTO employees) {
		this.employees = employees;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public Date getHireDate() {
		return this.hireDate;
	}

	public void setHireDate(Date hireDate) {
		this.hireDate = hireDate;
	}

	public BigDecimal getSalary() {
		return this.salary;
	}

	public void setSalary(BigDecimal salary) {
		this.salary = salary;
	}

	public BigDecimal getCommissionPct() {
		return this.commissionPct;
	}

	public void setCommissionPct(BigDecimal commissionPct) {
		this.commissionPct = commissionPct;
	}

	public Set<DepartmentsDTO> getDepartmentses() {
		return this.departmentses;
	}

	public void setDepartmentses(Set<DepartmentsDTO> departmentses) {
		this.departmentses = departmentses;
	}

	public Set<EmployeesDTO> getEmployeeses() {
		return this.employeeses;
	}

	public void setEmployeeses(Set<EmployeesDTO> employeeses) {
		this.employeeses = employeeses;
	}

	public Set<JobHistoryDTO> getJobHistories() {
		return this.jobHistories;
	}

	public void setJobHistories(Set<JobHistoryDTO> jobHistories) {
		this.jobHistories = jobHistories;
	}

}
