package com.ttx.my.spring.boot.data.jpa.thymleaf.dto;
// Generated Jul 17, 2016 1:38:06 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobHistory generated by hbm2java
 */
public class JobHistoryDTO implements java.io.Serializable {

	private JobHistoryIdDTO id;
	private DepartmentsDTO departments;
	private JobsDTO jobs;
	private EmployeesDTO employees;
	private Date endDate;

	public JobHistoryDTO() {
	}

	public JobHistoryIdDTO getId() {
		return id;
	}

	public void setId(JobHistoryIdDTO id) {
		this.id = id;
	}

	public DepartmentsDTO getDepartments() {
		return departments;
	}

	public void setDepartments(DepartmentsDTO departments) {
		this.departments = departments;
	}

	public EmployeesDTO getEmployees() {
		return employees;
	}

	public void setEmployees(EmployeesDTO employees) {
		this.employees = employees;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
