package com.ttx.my.spring.boot.data.jpa.thymleaf.dto;
// Generated Jul 17, 2016 1:38:06 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Jobs generated by hbm2java
 */
public class JobsDTO implements java.io.Serializable {

	private String jobId;
	private String jobTitle;
	private Integer minSalary;
	private Integer maxSalary;
	private Set<EmployeesDTO> employeeses = new HashSet<EmployeesDTO>(0);
	private Set<JobHistoryDTO> jobHistories = new HashSet<JobHistoryDTO>(0);

	public JobsDTO() {
	}

	public String getJobId() {
		return jobId;
	}

	public void setJobId(String jobId) {
		this.jobId = jobId;
	}

	public String getJobTitle() {
		return jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	public Integer getMinSalary() {
		return minSalary;
	}

	public void setMinSalary(Integer minSalary) {
		this.minSalary = minSalary;
	}

	public Integer getMaxSalary() {
		return maxSalary;
	}

	public void setMaxSalary(Integer maxSalary) {
		this.maxSalary = maxSalary;
	}

	public Set<EmployeesDTO> getEmployeeses() {
		return employeeses;
	}

	public void setEmployeeses(Set<EmployeesDTO> employeeses) {
		this.employeeses = employeeses;
	}

	public Set<JobHistoryDTO> getJobHistories() {
		return jobHistories;
	}

	public void setJobHistories(Set<JobHistoryDTO> jobHistories) {
		this.jobHistories = jobHistories;
	}

}
