package com.ttx.my.spring.boot.data.jpa.thymleaf.dto;
// Generated Jul 17, 2016 1:38:06 AM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Locations generated by hbm2java
 */
public class LocationsDTO implements java.io.Serializable {

	private short locationId;
	private CountriesDTO countries;
	private String streetAddress;
	private String postalCode;
	private String city;
	private String stateProvince;
	private Set<DepartmentsDTO> departmentses = new HashSet<DepartmentsDTO>(0);

	public LocationsDTO() {
	}

	public short getLocationId() {
		return locationId;
	}

	public void setLocationId(short locationId) {
		this.locationId = locationId;
	}

	public CountriesDTO getCountries() {
		return countries;
	}

	public void setCountries(CountriesDTO countries) {
		this.countries = countries;
	}

	public String getStreetAddress() {
		return streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	public String getPostalCode() {
		return postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getStateProvince() {
		return stateProvince;
	}

	public void setStateProvince(String stateProvince) {
		this.stateProvince = stateProvince;
	}

	public Set<DepartmentsDTO> getDepartmentses() {
		return departmentses;
	}

	public void setDepartmentses(Set<DepartmentsDTO> departmentses) {
		this.departmentses = departmentses;
	}

}
